ROUTINE QCMasterLib.Utils.REST.Swagger.Adapter [Type=INC]
#define NewLine							$CHAR(13,10)
#define OutputSwaggerObj				"pOutputSwaggerObj"
#define TempSwaggerObj					"tTempSwaggerObj"
#define	HostName						"pHostName"
#define	BasePath						"pBasePath"
#define HdrMapXDATAName					"HdrMap"
#define UrlMapXDATAName					"UrlMap"
#define MsgMapXDATAName					"MsgMap"
#define HdrMapXDATAElementsName			"Header"
#define UrlMapXDATARouteElementsName	"Route"
#define UrlMapXDATAMapElementsName		"Map"
#define MsgMapXDATARouteElementsName	"Route"
#define GenericRequestClassName			"QCMasterLib.Messages.Req.GenericUIReq"
#define GenericResponseClassName		"QCMasterLib.Messages.Rsp.GenericUIRsp"





#define DynamicJSONArrayProjection					"jsonarray"
#define DynamicNativeProjection						"native"
#define ArrayDynamicObjectProjectionModeParameter	"ArrayDynamicObjectMode"